### ISSUE TITLE
SS节点无法获取加密方式  

### ISSUE THREAD

**Issue by cnmars** [pingProMax/gov2panel#9]
2024/03/13 10:03:36 infra/conf: unknown cipher method: 
panic: infra/conf: unknown cipher method: 

{
	"port": "9996",
	"cypher_method": "chacha20-ietf-poly1305",
	"obfs": "none",
	"server_key":"",
	"obfs_settings": {
		"path": "",
		"host": ""
	}
}

试过了不行

2024/03/13 10:03:36 [Info] app/dns: DNS: created localhost client
2024/03/13 10:03:36 [Warning] core: Xray 1.8.9 started
&{map[cypher_method:chacha20-ietf-poly1305 flow_rate:1 obfs:none obfs_settings:map[host: path:] port:9996 routes:[map[action:dns action_value:8.8.8.8 id:6 match:[netflix.com]]] server_key:]}
&{Shadowsocks 7 9996 0 0 tcp    false false     [] [0xc0006e2ba0] false <nil>}
&{Shadowsocks 7 9996 0 0 tcp    false false     [] [0xc0006e2ba0] false <nil>}

**Comment by cnmars** [comment]
好了 有没有TG方便沟通

**Comment by cnmars** [comment]
INSERT INTO `v2_user`(`id`,`invite_user_id`,`telegram_id`,`user_name`,`password`,`password_algo`,`password_salt`,`balance`,`discount`,`commission_type`,`commission_rate`,`commission_balance`,`commission_code`,`t`,`u`,`d`,`transfer_enable`,`banned`,`is_admin`,`is_staff`,`last_login_at`,`last_login_ip`,`uuid`,`group_id`,`token`,`remarks`,`expired_at`,`created_at`,`updated_at`) VALUES(0,0,0,'test123@qq.com','273dfc79c72630bd771a25a2d808ad1b','MD5','97cdfb9b',0,0,3,0,0,'3948f1bd',0,0,0,0,-1,-1,-1,0,'','145657e0-463a-4d0b-b37f-e4e99ec80a50',0,'d8762a1d585e4c1ba666012a8b337fe2','',null,'2024-03-13 12:55:29','2024-03-13 12:55:29') : Error 1366 (HY000): Incorrect integer value: '' for column 'last_login_ip' at row 1


新用户注册会这样

**Comment by cnmars** [comment]
2024/03/13 12:53:55 Start the panel..
2024/03/13 12:53:55 Xray Core Version: 1.8.9
2024/03/13 12:53:55 [Warning] core: Xray 1.8.9 started
2024/03/13 12:53:55 Panel Start fialed: users is null
panic: Panel Start fialed: users is null

goroutine 1 [running]:
log.Panicf({0x10aef759c?, 0x10c118e20?}, {0xc000c17e18?, 0xc000319cb0?, 0x10b91dca0?})
        /Users/x/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.1.darwin-amd64/src/log/log.go:439 +0x65
github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc000472040)
        /Users/x/golang/2024/XrayR/panel/panel.go:210 +0x5cf

给管理员分配套餐 会显示无用户

**Comment by pingProMax** [comment]
> 插入`v2_user`( ,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,, )值( 0,0,0 , `id`' test123 @ qq.com ' , ' 273dfc79c72630bd771a25a2d808ad1b​​​​​​​​​​​​​​​[​](mailto:test123@qq.com) ​','MD5','97cdfb9b',0,0,3,0,0,'3948f1bd',0,0,0,0,-1,-1,-1,0,'','145657e0-463a -4d0b-b37f-e4e99ec80a50',0,'d8762a1d585e4c1ba666012a8b337fe2','',null,'2024-03-13 12:55:29','2024-03-13 12:55:29') : 错误 1366 (HY000 ): 不正确的整数值：第 1 行的“last_login_ip”列的“”`invite_user_id``telegram_id``user_name``password``password_algo``password_salt``balance``discount``commission_type``commission_rate``commission_balance``commission_code``t``u``d``transfer_enable``banned``is_admin``is_staff``last_login_at``last_login_ip``uuid``group_id``token``remarks``expired_at``created_at``updated_at`[](mailto:test123@qq.com)
> 
> 新注册用户会这样

sql在我库里面执行正常 你试试update.sql 升级一下或者重新导下库

**Comment by pingProMax** [comment]
> 2024/03/13 12:53:55 Start the panel.. 2024/03/13 12:53:55 Xray Core Version: 1.8.9 2024/03/13 12:53:55 [Warning] core: Xray 1.8.9 started 2024/03/13 12:53:55 Panel Start fialed: users is null panic: Panel Start fialed: users is null
> 
> goroutine 1 [running]: log.Panicf({0x10aef759c?, 0x10c118e20?}, {0xc000c17e18?, 0xc000319cb0?, 0x10b91dca0?}) /Users/x/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.1.darwin-amd64/src/log/log.go:439 +0x65 github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc000472040) /Users/x/golang/2024/XrayR/panel/panel.go:210 +0x5cf
> 
> 给管理员分配套餐 会显示无用户

到期时间，剩余流量，是否冻结

**Comment by cnmars** [comment]
什么时候可以支持CLASH订阅链接 还有 商品可以做成不限时的吗

**Comment by pingProMax** [comment]
> 品可以做

可以做不限时，你把过期时间调2099不就行了，CLASH订阅链接没找到文档

**Comment by cnmars** [comment]
https://github.com/ppoonk/AirGo 参考这个订阅 很全了

**Comment by pingProMax** [comment]
> https://github.com/ppoonk/AirGo 参考这个订阅 很全了

我给加加试试

**Comment by cnmars** [comment]
vmess://eyJhZGQiOiIxMjcuMC4wLjEiLCJhaWQiOiIwIiwiaWQiOiI1Y2JiYjYxMS1jM2MyLTRmMmUtYmE5MS1iYjBkNjA3MmQyMGIiLCJwb3J0IjoiODAiLCJwcyI6IuWll+mkkOWIsOacn++8mjIwMjktMDktMDMgMTA6MzkiLCJ2IjoiMiJ9
vmess://eyJhZGQiOiIxMjcuMC4wLjEiLCJhaWQiOiIwIiwiYWxwbiI6IiIsImZwIjoiIiwiaG9zdCI6IiIsImlkIjoiNWNiYmI2MTEtYzNjMi00ZjJlLWJhOTEtYmIwZDYwNzJkMjBiIiwibmV0IjoidGNwIiwicGF0aCI6IiIsInBvcnQiOiI4MCIsInBzIjoi5Ymp5L2Z5rWB6YeP77yaMTAwLjAwIEdCIiwic2N5IjoiIiwic25pIjoiIiwidGxzIjoiIiwidHlwZSI6Im5vbmUiLCJ2IjoiMiJ9
ss://YWVzLTEyOC1nY206NWNiYmI2MTEtYzNjMi00ZjJlLWJhOTEtYmIwZDYwNzJkMjBi@1.1.1.1:18080#test




SS 节点生成 后 剩余流量到期时间节点还是vmess并没有跟随SS

**Comment by pingProMax** [comment]
> vmess://eyJhZGQiOiIxMjcuMC4wLjEiLCJhaWQiOiIwIiwiaWQiOiI1Y2JiYjYxMS1jM2MyLTRmMmUtYmE5MS1iYjBkNjA3MmQyMGIiLCJwb3J0IjoiODAiLCJwcyI6IuWll+mkkOWIsOacn++8mjIwMjktMDktMDMgMTA6MzkiLCJ2IjoiMiJ9 vmess://eyJhZGQiOiIxMjcuMC4wLjEiLCJhaWQiOiIwIiwiYWxwbiI6IiIsImZwIjoiIiwiaG9zdCI6IiIsImlkIjoiNWNiYmI2MTEtYzNjMi00ZjJlLWJhOTEtYmIwZDYwNzJkMjBiIiwibmV0IjoidGNwIiwicGF0aCI6IiIsInBvcnQiOiI4MCIsInBzIjoi5Ymp5L2Z5rWB6YeP77yaMTAwLjAwIEdCIiwic2N5IjoiIiwic25pIjoiIiwidGxzIjoiIiwidHlwZSI6Im5vbmUiLCJ2IjoiMiJ9 ss://YWVzLTEyOC1nY206NWNiYmI2MTEtYzNjMi00ZjJlLWJhOTEtYmIwZDYwNzJkMjBi@1.1.1.1:18080#test
> 
> SS 节点生成 后 剩余流量到期时间节点还是vmess并没有跟随SS

明白你的意思了，用的是ss客户端是把，我这默认用v2rayN去测试的，我去改改罗

**Comment by cnmars** [comment]
SS节点状态发现还是红的节点对接后没有变化

**Comment by pingProMax** [comment]
> SS节点状态发现还是红的节点对接后没有变化

xrayr日志贴出来看看

**Comment by cnmars** [comment]
就是正常增加删除用户日志 我观察一会 那个点还是红的

**Comment by pingProMax** [comment]
> 就是正常增加删除用户日志 我观察一会 那个点还是红的

节点能用吗
